<?php /** @var \Openpay\CheckoutLending\Block\Cancelled $block */ ?>

    <div style="margin:auto; padding:10px; text-align:center;" class="container">
        <img style="width: 100%;" data-bind="attr: { src: require.toUrl('Openpay_CheckoutLending/img/cancelled.png') }" alt="">
<?php if ($block->getData('error_msg')) : ?>
    <h2 style="text-align:center; font-weight:bold"><?php echo __($block->getData('error_msg')) ?></h2>
<?php else : ?>
        <h2 style="text-align:center; font-weight:bold" >Su orden fue cancelada</h2>
<?php endif; ?>
    </div>



